version: '3'

services:
  db:
    image: postgres:latest
    expose:
      - "5432"
    env_file: run/scionlab.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: deploy/Dockerfile-django
    env_file: run/scionlab.env
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./run/:/scionlab/run/:z
      - web-static:/scionlab/static/:z

  caddy:
    image: caddy:2.4.6-alpine
    env_file: run/scionlab.env
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:z
      - web-static:/srv/scionlab/static:z
      - caddydata:/data

volumes:
  web-static:
  caddydata:
  pgdata:
